<?php
/**
 * Teacher Profile ACF Field Group
 *
 * Registers a complete teacher profile field group using ACF PRO.
 * All data is stored as user meta for MasterStudy instructor users.
 *
 * @package MKH_Teacher_Addon
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Registers the Teacher Profile field group with ACF PRO.
 *
 * This class creates a comprehensive field group for instructor profiles
 * including basic information, about section, teaching skills, employment
 * history, certifications, and ijazah records.
 */
class MKH_Teacher_Profile_ACF {

	/**
	 * Instructor role used for field group visibility.
	 *
	 * MasterStudy LMS uses 'stm_lms_instructor' as the instructor role.
	 * Change this value if your installation uses a different role.
	 *
	 * @var string
	 */
	protected $instructor_role = 'stm_lms_instructor';

	/**
	 * Constructor.
	 *
	 * Hooks into ACF init to register the field group.
	 */
	public function __construct() {
		add_action( 'acf/init', array( $this, 'register_fields' ) );
	}

	/**
	 * Register the field group if ACF is available.
	 *
	 * Only registers if acf_add_local_field_group function exists,
	 * ensuring compatibility with ACF PRO 6.x.
	 */
	public function register_fields() {
		if ( ! function_exists( 'acf_add_local_field_group' ) ) {
			return;
		}

		$field_group = array(
			'key'                   => 'group_mkh_teacher_profile',
			'title'                 => esc_html__( 'Teacher Profile', 'mkh-teacher-addon' ),
			'fields'                => $this->get_fields(),
			'location'              => array(
				array(
					array(
						'param'    => 'user_form',
						'operator' => '==',
						'value'    => 'edit',
					),
					array(
						'param'    => 'user_role',
						'operator' => '==',
						'value'    => $this->instructor_role,
					),
				),
				array(
					array(
						'param'    => 'user_form',
						'operator' => '==',
						'value'    => 'edit',
					),
					array(
						'param'    => 'user_role',
						'operator' => '==',
						'value'    => 'administrator',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(),
			'active'                => true,
			'description'          => esc_html__( 'Extended instructor profile data stored as user meta.', 'mkh-teacher-addon' ),
		);

		acf_add_local_field_group( $field_group );
	}

	/**
	 * Build the field definitions.
	 *
	 * @return array<int, array<string, mixed>> Field definitions.
	 */
	private function get_fields() {
		$fields = array();

		// ========================================
		// SECTION 1: BASIC INFORMATION
		// ========================================

		// Tab for Basic Information
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_tab_basic',
			'name'          => 'mkh_teacher_profile_tab_basic',
			'label'         => esc_html__( 'Basic Information', 'mkh-teacher-addon' ),
			'type'          => 'tab',
			'instructions'  => esc_html__( 'Core instructor profile information.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'placement'     => 'top',
			'endpoint'      => 0,
		);

		// Accordion for Basic Information
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_accordion_basic',
			'name'          => 'mkh_teacher_profile_accordion_basic',
			'label'         => esc_html__( 'Basic Information', 'mkh-teacher-addon' ),
			'type'          => 'accordion',
			'instructions'  => esc_html__( 'Add the basic details teachers use to present themselves.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'open'          => 1,
			'multi_expand'  => 0,
			'endpoint'      => 0,
		);

		// About Teacher Field (moved from About section)
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_about',
			'name'          => 'about_teacher',
			'label'         => esc_html__( 'About Teacher', 'mkh-teacher-addon' ),
			'type'          => 'textarea',
			'instructions'  => esc_html__( 'Write a clear introduction that highlights experience, teaching approach, and character.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'wrapper'       => array( 'width' => '100' ),
			'rows'          => 8,
			'maxlength'     => 1000,
		);



		// Age Field (50% width for side-by-side layout)
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_age',
			'name'          => 'mkh_age',
			'label'         => esc_html__( 'Age', 'mkh-teacher-addon' ),
			'type'          => 'number',
			'required'      => 0,
			'wrapper'       => array( 'width' => '50' ),
			'min'           => 16,
			'max'           => 100,
			'step'          => 1,
			'placeholder'   => esc_html__( 'Enter Age', 'mkh-teacher-addon' ),
		);

		// Gender Field (50% width for side-by-side layout)
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_gender',
			'name'          => 'mkh_gender',
			'label'         => esc_html__( 'Gender', 'mkh-teacher-addon' ),
			'type'          => 'select',
			'required'      => 0,
			'wrapper'       => array( 'width' => '50' ),
			'choices'       => array(
				'male'             => esc_html__( 'Male', 'mkh-teacher-addon' ),
				'female'           => esc_html__( 'Female', 'mkh-teacher-addon' ),
				'prefer_not_to_say' => esc_html__( 'Prefer not to say', 'mkh-teacher-addon' ),
			),
			'default_value' => '',
			'allow_null'    => 1,
			'multiple'      => 0,
			'ui'            => 1,
			'return_format' => 'value',
		);

		// Country Field (50% width for side-by-side layout)
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_country',
			'name'          => 'mkh_country',
			'label'         => esc_html__( 'Country', 'mkh-teacher-addon' ),
			'type'          => 'select',
			'required'      => 0,
			'wrapper'       => array( 'width' => '50' ),
			'choices'       => $this->get_country_choices(),
			'default_value' => '',
			'allow_null'    => 1,
			'multiple'      => 0,
			'ui'            => 1,
			'return_format' => 'value',
		);

		// Timezone Field (50% width for side-by-side layout)
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_timezone',
			'name'          => 'mkh_timezone',
			'label'         => esc_html__( 'Timezone', 'mkh-teacher-addon' ),
			'type'          => 'select',
			'required'      => 0,
			'wrapper'       => array( 'width' => '50' ),
			'choices'       => $this->get_timezone_choices(),
			'default_value' => '',
			'allow_null'    => 1,
			'multiple'      => 0,
			'ui'            => 1,
			'return_format' => 'value',
		);
	

		// Teacher Photo Field
/* 		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_photo',
			'name'          => 'teacher_photo',
			'label'         => esc_html__( 'Teacher Photo', 'mkh-teacher-addon' ),
			'type'          => 'image',
			'instructions'  => esc_html__( 'Upload an image that will be shown on the teacher profile page.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'wrapper'       => array( 'width' => '50' ),
			'return_format' => 'array',
			'preview_size'  => 'medium',
			'library'       => 'all',
			'mime_types'    => 'jpg,jpeg,png,webp',
		); */

		// Recitation Audio Field
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_audio',
			'name'          => 'recitation_audio',
			'label'         => esc_html__( 'Recitation Audio', 'mkh-teacher-addon' ),
			'type'          => 'file',
			'instructions'  => esc_html__( 'Upload an audio file for recitation or sample content.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'wrapper'       => array( 'width' => '50' ),
			'return_format' => 'array',
			'library'       => 'all',
			'mime_types'    => 'mp3,wav,m4a',
		);

		// Intro Video File Field
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_intro_video_file',
			'name'          => 'intro_video_file',
			'label'         => esc_html__( 'Intro Video File', 'mkh-teacher-addon' ),
			'type'          => 'file',
			'instructions'  => esc_html__( 'Upload an introduction video file if you prefer to host it locally.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'wrapper'       => array( 'width' => '50' ),
			'return_format' => 'array',
			'library'       => 'all',
			'mime_types'    => 'mp4,mov,webm',
		);

		// Intro Video URL Field
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_intro_video_url',
			'name'          => 'intro_video_url',
			'label'         => esc_html__( 'Intro Video URL', 'mkh-teacher-addon' ),
			'type'          => 'url',
			'instructions'  => esc_html__( 'Paste a remote video URL if you prefer to use a hosted video instead of a file upload.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'wrapper'       => array( 'width' => '50' ),
			'return_format' => 'url',
		);
		// Languages Field (changed to Multi-Select)
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_languages',
			'name'          => 'languages',
			'label'         => esc_html__( 'Languages', 'mkh-teacher-addon' ),
			'type'          => 'select',
			'instructions'  => esc_html__( 'Select the languages you teach or communicate in.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'wrapper'       => array( 'width' => '50' ),
			'choices'       => array(
				'english'    => esc_html__( 'English', 'mkh-teacher-addon' ),
				'arabic'     => esc_html__( 'Arabic', 'mkh-teacher-addon' ),
				'urdu'       => esc_html__( 'Urdu', 'mkh-teacher-addon' ),
				'hindi'      => esc_html__( 'Hindi', 'mkh-teacher-addon' ),
				'punjabi'    => esc_html__( 'Punjabi', 'mkh-teacher-addon' ),
				'turkish'    => esc_html__( 'Turkish', 'mkh-teacher-addon' ),
				'bengali'    => esc_html__( 'Bengali', 'mkh-teacher-addon' ),
				'persian'    => esc_html__( 'Persian', 'mkh-teacher-addon' ),
				'pashto'     => esc_html__( 'Pashto', 'mkh-teacher-addon' ),
				'malay'      => esc_html__( 'Malay', 'mkh-teacher-addon' ),
				'indonesian' => esc_html__( 'Indonesian', 'mkh-teacher-addon' ),
				'french'     => esc_html__( 'French', 'mkh-teacher-addon' ),
			),
			'allow_custom'  => 0,
			'multiple'      => 1,
			'ui'            => 1,
			'ajax'          => 0,
			'placeholder'  => esc_html__( 'Select languages', 'mkh-teacher-addon' ),
			'return_format' => 'array',
		);
	// Fiqh Field (50% width for side-by-side layout)
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_fiqh',
			'name'          => 'fiqh',
			'label'         => esc_html__( 'Fiqh', 'mkh-teacher-addon' ),
			'type'          => 'select',
			'instructions'  => esc_html__( 'Select the madhhab the teacher follows.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'wrapper'       => array( 'width' => '25' ),
			'choices'       => array(
				'hanafi' => esc_html__( 'Hanafi', 'mkh-teacher-addon' ),
				'shafi'  => esc_html__( 'Shafi', 'mkh-teacher-addon' ),
				'maliki' => esc_html__( 'Maliki', 'mkh-teacher-addon' ),
				'hanbali' => esc_html__( 'Hanbali', 'mkh-teacher-addon' ),
			),
			'default_value' => '',
			'allow_null'    => 1,
			'multiple'      => 0,
			'ui'            => 1,
			'return_format' => 'value',
		);

		// Sect Field (50% width for side-by-side layout)
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_sect',
			'name'          => 'sect',
			'label'         => esc_html__( 'Sect', 'mkh-teacher-addon' ),
			'type'          => 'text',
			'instructions'  => esc_html__( 'Enter the teacher\'s sect or school affiliation.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'wrapper'       => array( 'width' => '25' ),
			'placeholder'   => esc_html__( 'Enter Sect', 'mkh-teacher-addon' ),
		);
		// Hourly Rate Field (moved to last position)
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_hourly_rate',
			'name'          => 'hourly_rate',
			'label'         => esc_html__( 'Hourly Rate', 'mkh-teacher-addon' ),
			'type'          => 'number',
			'instructions'  => esc_html__( 'Enter the standard hourly teaching rate. This amount will be displayed on the public instructor profile.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'wrapper'       => array( 'width' => '50' ),
			'prepend'       => '$',
			'min'           => 0,
			'step'          => 1,
			'return_format' => 'float',
		);

		// ========================================
		// SECTION 2: TEACHING SKILLS
		// ========================================

		// Tab for Teaching Skills
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_tab_skills',
			'name'          => 'mkh_teacher_profile_tab_skills',
			'label'         => esc_html__( 'Teaching Skills', 'mkh-teacher-addon' ),
			'type'          => 'tab',
			'instructions'  => esc_html__( 'Skills and specializations offered by the teacher.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'placement'     => 'top',
			'endpoint'      => 0,
		);

		// Accordion for Teaching Skills
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_accordion_skills',
			'name'          => 'mkh_teacher_profile_accordion_skills',
			'label'         => esc_html__( 'Teaching Skills', 'mkh-teacher-addon' ),
			'type'          => 'accordion',
			'instructions'  => esc_html__( 'Select the teaching specializations that best describe this teacher.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'open'          => 1,
			'multi_expand'  => 0,
			'endpoint'      => 0,
		);

		// Teaching Skills Field
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_skills',
			'name'          => 'teaching_skills',
			'label'         => esc_html__( 'Teaching Skills', 'mkh-teacher-addon' ),
			'type'          => 'checkbox',
			'instructions'  => esc_html__( 'Choose the areas the teacher is best known for.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'wrapper'       => array( 'width' => '100' ),
			'choices'       => array(
				'recitation' => esc_html__( 'Recitation', 'mkh-teacher-addon' ),
				'hifz'       => esc_html__( 'Hifz', 'mkh-teacher-addon' ),
				'arabic'     => esc_html__( 'Arabic', 'mkh-teacher-addon' ),
				'tajweed'    => esc_html__( 'Tajweed', 'mkh-teacher-addon' ),
			),
			'allow_custom'  => 0,
			'layout'        => 'vertical',
			'return_format' => 'array',
		);

		// ========================================
		// SECTION 3: EMPLOYMENT HISTORY
		// ========================================

		// Tab for Employment History
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_tab_employment',
			'name'          => 'mkh_teacher_profile_tab_employment',
			'label'         => esc_html__( 'Employment History', 'mkh-teacher-addon' ),
			'type'          => 'tab',
			'instructions'  => esc_html__( 'Professional employment history and previous institutions.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'placement'     => 'top',
			'endpoint'      => 0,
		);

		// Accordion for Employment History
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_accordion_employment',
			'name'          => 'mkh_teacher_profile_accordion_employment',
			'label'         => esc_html__( 'Employment History', 'mkh-teacher-addon' ),
			'type'          => 'accordion',
			'instructions'  => esc_html__( 'Add prior roles and teaching positions in a structured format.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'open'          => 1,
			'multi_expand'  => 0,
			'endpoint'      => 0,
		);

		// Employment History Repeater
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_employment_history',
			'name'          => 'employment_history',
			'label'         => esc_html__( 'Employment History', 'mkh-teacher-addon' ),
			'type'          => 'repeater',
			'instructions'  => esc_html__( 'Add any past schools, institutes, or teaching roles.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'wrapper'       => array( 'width' => '100' ),
			'button_label'  => esc_html__( 'Add Employment', 'mkh-teacher-addon' ),
			'collapsed'     => 'field_mkh_teacher_profile_employment_institute',
			'min'           => 0,
			'layout'        => 'block',
			'sub_fields'    => array(
				array(
					'key'           => 'field_mkh_teacher_profile_employment_institute',
					'name'          => 'institute',
					'label'         => esc_html__( 'Institute', 'mkh-teacher-addon' ),
					'type'          => 'text',
					'instructions'  => esc_html__( 'Name of the institution or organization.', 'mkh-teacher-addon' ),
					'required'      => 0,
					'wrapper'       => array( 'width' => '50' ),
				),
				array(
					'key'           => 'field_mkh_teacher_profile_employment_position',
					'name'          => 'position',
					'label'         => esc_html__( 'Position', 'mkh-teacher-addon' ),
					'type'          => 'text',
					'instructions'  => esc_html__( 'Role or title held during this appointment.', 'mkh-teacher-addon' ),
					'required'      => 0,
					'wrapper'       => array( 'width' => '50' ),
				),
				array(
					'key'           => 'field_mkh_teacher_profile_employment_from',
					'name'          => 'from_date',
					'label'         => esc_html__( 'From Date', 'mkh-teacher-addon' ),
					'type'          => 'date_picker',
					'instructions'  => esc_html__( 'Start date for this role.', 'mkh-teacher-addon' ),
					'required'      => 0,
					'wrapper'       => array( 'width' => '50' ),
					'return_format' => 'Y-m-d',
					'display_format' => 'Y-m-d',
				),
				array(
					'key'           => 'field_mkh_teacher_profile_employment_to',
					'name'          => 'to_date',
					'label'         => esc_html__( 'To Date', 'mkh-teacher-addon' ),
					'type'          => 'date_picker',
					'instructions'  => esc_html__( 'End date for this role.', 'mkh-teacher-addon' ),
					'required'      => 0,
					'wrapper'       => array( 'width' => '50' ),
					'return_format' => 'Y-m-d',
					'display_format' => 'Y-m-d',
				),
				array(
					'key'           => 'field_mkh_teacher_profile_employment_description',
					'name'          => 'description',
					'label'         => esc_html__( 'Description', 'mkh-teacher-addon' ),
					'type'          => 'textarea',
					'instructions'  => esc_html__( 'Add a short summary of the work completed here.', 'mkh-teacher-addon' ),
					'required'      => 0,
					'wrapper'       => array( 'width' => '100' ),
					'rows'          => 4,
				),
			),
		);

		// ========================================
		// SECTION 4: CERTIFICATIONS
		// ========================================

		// Tab for Certifications
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_tab_certifications',
			'name'          => 'mkh_teacher_profile_tab_certifications',
			'label'         => esc_html__( 'Certifications', 'mkh-teacher-addon' ),
			'type'          => 'tab',
			'instructions'  => esc_html__( 'Academic and professional certifications.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'placement'     => 'top',
			'endpoint'      => 0,
		);

		// Accordion for Certifications
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_accordion_certifications',
			'name'          => 'mkh_teacher_profile_accordion_certifications',
			'label'         => esc_html__( 'Certifications', 'mkh-teacher-addon' ),
			'type'          => 'accordion',
			'instructions'  => esc_html__( 'List certifications and accompanying documents.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'open'          => 1,
			'multi_expand'  => 0,
			'endpoint'      => 0,
		);

		// Certifications Repeater
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_certifications',
			'name'          => 'certifications',
			'label'         => esc_html__( 'Certifications', 'mkh-teacher-addon' ),
			'type'          => 'repeater',
			'instructions'  => esc_html__( 'Add notable certifications and qualifications.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'wrapper'       => array( 'width' => '100' ),
			'button_label'  => esc_html__( 'Add Certification', 'mkh-teacher-addon' ),
			'collapsed'     => 'field_mkh_teacher_profile_certification_title',
			'min'           => 0,
			'layout'        => 'block',
			'sub_fields'    => array(
				array(
					'key'           => 'field_mkh_teacher_profile_certification_title',
					'name'          => 'title',
					'label'         => esc_html__( 'Title', 'mkh-teacher-addon' ),
					'type'          => 'text',
					'instructions'  => esc_html__( 'Certification title or credential name.', 'mkh-teacher-addon' ),
					'required'      => 0,
					'wrapper'       => array( 'width' => '50' ),
				),
				array(
					'key'           => 'field_mkh_teacher_profile_certification_issued_by',
					'name'          => 'issued_by',
					'label'         => esc_html__( 'Issued By', 'mkh-teacher-addon' ),
					'type'          => 'text',
					'instructions'  => esc_html__( 'Name of the issuing authority or organization.', 'mkh-teacher-addon' ),
					'required'      => 0,
					'wrapper'       => array( 'width' => '50' ),
				),
				array(
					'key'           => 'field_mkh_teacher_profile_certification_year',
					'name'          => 'year',
					'label'         => esc_html__( 'Year', 'mkh-teacher-addon' ),
					'type'          => 'number',
					'instructions'  => esc_html__( 'Year the certification was issued.', 'mkh-teacher-addon' ),
					'required'      => 0,
					'wrapper'       => array( 'width' => '50' ),
					'min'           => 1900,
					'max'           => absint( wp_date( 'Y' ) ),
				),
				array(
					'key'           => 'field_mkh_teacher_profile_certification_file',
					'name'          => 'certificate_file',
					'label'         => esc_html__( 'Certificate File', 'mkh-teacher-addon' ),
					'type'          => 'file',
					'instructions'  => esc_html__( 'Upload an official certificate or credential document.', 'mkh-teacher-addon' ),
					'required'      => 0,
					'wrapper'       => array( 'width' => '50' ),
					'return_format' => 'array',
					'library'       => 'all',
					'mime_types'    => 'pdf,jpg,jpeg,png',
				),
			),
		);

		// ========================================
		// SECTION 5: IJAZAH
		// ========================================

		// Tab for Ijazah
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_tab_ijazah',
			'name'          => 'mkh_teacher_profile_tab_ijazah',
			'label'         => esc_html__( 'Ijazah', 'mkh-teacher-addon' ),
			'type'          => 'tab',
			'instructions'  => esc_html__( 'Ijazah and religious authorization records.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'placement'     => 'top',
			'endpoint'      => 0,
		);

		// Accordion for Ijazah
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_accordion_ijazah',
			'name'          => 'mkh_teacher_profile_accordion_ijazah',
			'label'         => esc_html__( 'Ijazah', 'mkh-teacher-addon' ),
			'type'          => 'accordion',
			'instructions'  => esc_html__( 'Record ijazah details and supporting documents.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'open'          => 1,
			'multi_expand'  => 0,
			'endpoint'      => 0,
		);

		// Ijazah Repeater
		$fields[] = array(
			'key'           => 'field_mkh_teacher_profile_ijazah',
			'name'          => 'ijazah',
			'label'         => esc_html__( 'Ijazah', 'mkh-teacher-addon' ),
			'type'          => 'repeater',
			'instructions'  => esc_html__( 'Add each ijazah, authorization, or sanad received.', 'mkh-teacher-addon' ),
			'required'      => 0,
			'wrapper'       => array( 'width' => '100' ),
			'button_label'  => esc_html__( 'Add Ijazah', 'mkh-teacher-addon' ),
			'collapsed'     => 'field_mkh_teacher_profile_ijazah_title',
			'min'           => 0,
			'layout'        => 'block',
			'sub_fields'    => array(
				array(
					'key'           => 'field_mkh_teacher_profile_ijazah_title',
					'name'          => 'title',
					'label'         => esc_html__( 'Title', 'mkh-teacher-addon' ),
					'type'          => 'text',
					'instructions'  => esc_html__( 'Name of the ijazah or certificate.', 'mkh-teacher-addon' ),
					'required'      => 0,
					'wrapper'       => array( 'width' => '50' ),
				),
				array(
					'key'           => 'field_mkh_teacher_profile_ijazah_granted_by',
					'name'          => 'granted_by',
					'label'         => esc_html__( 'Granted By', 'mkh-teacher-addon' ),
					'type'          => 'text',
					'instructions'  => esc_html__( 'Person or institution that granted the ijazah.', 'mkh-teacher-addon' ),
					'required'      => 0,
					'wrapper'       => array( 'width' => '50' ),
				),
				array(
					'key'           => 'field_mkh_teacher_profile_ijazah_date',
					'name'          => 'date',
					'label'         => esc_html__( 'Date', 'mkh-teacher-addon' ),
					'type'          => 'date_picker',
					'instructions'  => esc_html__( 'Date the ijazah was granted.', 'mkh-teacher-addon' ),
					'required'      => 0,
					'wrapper'       => array( 'width' => '50' ),
					'return_format' => 'Y-m-d',
					'display_format' => 'Y-m-d',
				),
				array(
					'key'           => 'field_mkh_teacher_profile_ijazah_file',
					'name'          => 'upload_file',
					'label'         => esc_html__( 'Upload File', 'mkh-teacher-addon' ),
					'type'          => 'file',
					'instructions'  => esc_html__( 'Attach a supporting document or certificate.', 'mkh-teacher-addon' ),
					'required'      => 0,
					'wrapper'       => array( 'width' => '50' ),
					'return_format' => 'array',
					'library'       => 'all',
					'mime_types'    => 'pdf,jpg,jpeg,png',
				),
			),
		);

		// ========================================
		// FUTURE EXTENSIONS
		// ========================================
		// Additional sections can be added here without refactoring existing code:
		// - Availability Schedule
		// - Trial Class Settings
		// - Teaching Experience
		// - Student Levels
		// - Gender Preference
		// - Country
		// - Time Zone
		// ========================================

		return $fields;
	}

	/**
	 * Get country choices for select field.
	 *
	 * @return array<string, string> Country choices.
	 */
	private function get_country_choices() {
		$countries = array(
			'AF' => esc_html__( 'Afghanistan', 'mkh-teacher-addon' ),
			'AL' => esc_html__( 'Albania', 'mkh-teacher-addon' ),
			'DZ' => esc_html__( 'Algeria', 'mkh-teacher-addon' ),
			'AS' => esc_html__( 'American Samoa', 'mkh-teacher-addon' ),
			'AD' => esc_html__( 'Andorra', 'mkh-teacher-addon' ),
			'AO' => esc_html__( 'Angola', 'mkh-teacher-addon' ),
			'AI' => esc_html__( 'Anguilla', 'mkh-teacher-addon' ),
			'AQ' => esc_html__( 'Antarctica', 'mkh-teacher-addon' ),
			'AG' => esc_html__( 'Antigua and Barbuda', 'mkh-teacher-addon' ),
			'AR' => esc_html__( 'Argentina', 'mkh-teacher-addon' ),
			'AM' => esc_html__( 'Armenia', 'mkh-teacher-addon' ),
			'AW' => esc_html__( 'Aruba', 'mkh-teacher-addon' ),
			'AU' => esc_html__( 'Australia', 'mkh-teacher-addon' ),
			'AT' => esc_html__( 'Austria', 'mkh-teacher-addon' ),
			'AZ' => esc_html__( 'Azerbaijan', 'mkh-teacher-addon' ),
			'BS' => esc_html__( 'Bahamas', 'mkh-teacher-addon' ),
			'BH' => esc_html__( 'Bahrain', 'mkh-teacher-addon' ),
			'BD' => esc_html__( 'Bangladesh', 'mkh-teacher-addon' ),
			'BB' => esc_html__( 'Barbados', 'mkh-teacher-addon' ),
			'BY' => esc_html__( 'Belarus', 'mkh-teacher-addon' ),
			'BE' => esc_html__( 'Belgium', 'mkh-teacher-addon' ),
			'BZ' => esc_html__( 'Belize', 'mkh-teacher-addon' ),
			'BJ' => esc_html__( 'Benin', 'mkh-teacher-addon' ),
			'BM' => esc_html__( 'Bermuda', 'mkh-teacher-addon' ),
			'BT' => esc_html__( 'Bhutan', 'mkh-teacher-addon' ),
			'BO' => esc_html__( 'Bolivia', 'mkh-teacher-addon' ),
			'BA' => esc_html__( 'Bosnia and Herzegovina', 'mkh-teacher-addon' ),
			'BW' => esc_html__( 'Botswana', 'mkh-teacher-addon' ),
			'BV' => esc_html__( 'Bouvet Island', 'mkh-teacher-addon' ),
			'BR' => esc_html__( 'Brazil', 'mkh-teacher-addon' ),
			'IO' => esc_html__( 'British Indian Ocean Territory', 'mkh-teacher-addon' ),
			'BN' => esc_html__( 'Brunei Darussalam', 'mkh-teacher-addon' ),
			'BG' => esc_html__( 'Bulgaria', 'mkh-teacher-addon' ),
			'BF' => esc_html__( 'Burkina Faso', 'mkh-teacher-addon' ),
			'BI' => esc_html__( 'Burundi', 'mkh-teacher-addon' ),
			'KH' => esc_html__( 'Cambodia', 'mkh-teacher-addon' ),
			'CM' => esc_html__( 'Cameroon', 'mkh-teacher-addon' ),
			'CA' => esc_html__( 'Canada', 'mkh-teacher-addon' ),
			'CV' => esc_html__( 'Cape Verde', 'mkh-teacher-addon' ),
			'KY' => esc_html__( 'Cayman Islands', 'mkh-teacher-addon' ),
			'TD' => esc_html__( 'Chad', 'mkh-teacher-addon' ),
			'CL' => esc_html__( 'Chile', 'mkh-teacher-addon' ),
			'CN' => esc_html__( 'China', 'mkh-teacher-addon' ),
			'CX' => esc_html__( 'Christmas Island', 'mkh-teacher-addon' ),
			'CC' => esc_html__( 'Cocos (Keeling) Islands', 'mkh-teacher-addon' ),
			'CO' => esc_html__( 'Colombia', 'mkh-teacher-addon' ),
			'KM' => esc_html__( 'Comoros', 'mkh-teacher-addon' ),
			'CG' => esc_html__( 'Congo', 'mkh-teacher-addon' ),
			'CK' => esc_html__( 'Cook Islands', 'mkh-teacher-addon' ),
			'CR' => esc_html__( 'Costa Rica', 'mkh-teacher-addon' ),
			'CI' => esc_html__( 'Cote D\'Ivoire', 'mkh-teacher-addon' ),
			'HR' => esc_html__( 'Croatia', 'mkh-teacher-addon' ),
			'CU' => esc_html__( 'Cuba', 'mkh-teacher-addon' ),
			'CY' => esc_html__( 'Cyprus', 'mkh-teacher-addon' ),
			'CZ' => esc_html__( 'Czech Republic', 'mkh-teacher-addon' ),
			'DK' => esc_html__( 'Denmark', 'mkh-teacher-addon' ),
			'DJ' => esc_html__( 'Djibouti', 'mkh-teacher-addon' ),
			'DM' => esc_html__( 'Dominica', 'mkh-teacher-addon' ),
			'DO' => esc_html__( 'Dominican Republic', 'mkh-teacher-addon' ),
			'EC' => esc_html__( 'Ecuador', 'mkh-teacher-addon' ),
			'EG' => esc_html__( 'Egypt', 'mkh-teacher-addon' ),
			'SV' => esc_html__( 'El Salvador', 'mkh-teacher-addon' ),
			'GQ' => esc_html__( 'Equatorial Guinea', 'mkh-teacher-addon' ),
			'ER' => esc_html__( 'Eritrea', 'mkh-teacher-addon' ),
			'EE' => esc_html__( 'Estonia', 'mkh-teacher-addon' ),
			'ET' => esc_html__( 'Ethiopia', 'mkh-teacher-addon' ),
			'FK' => esc_html__( 'Falkland Islands (Malvinas)', 'mkh-teacher-addon' ),
			'FO' => esc_html__( 'Faroe Islands', 'mkh-teacher-addon' ),
			'FJ' => esc_html__( 'Fiji', 'mkh-teacher-addon' ),
			'FI' => esc_html__( 'Finland', 'mkh-teacher-addon' ),
			'FR' => esc_html__( 'France', 'mkh-teacher-addon' ),
			'GF' => esc_html__( 'French Guiana', 'mkh-teacher-addon' ),
			'PF' => esc_html__( 'French Polynesia', 'mkh-teacher-addon' ),
			'TF' => esc_html__( 'French Southern Territories', 'mkh-teacher-addon' ),
			'GA' => esc_html__( 'Gabon', 'mkh-teacher-addon' ),
			'GM' => esc_html__( 'Gambia', 'mkh-teacher-addon' ),
			'GE' => esc_html__( 'Georgia', 'mkh-teacher-addon' ),
			'DE' => esc_html__( 'Germany', 'mkh-teacher-addon' ),
			'GH' => esc_html__( 'Ghana', 'mkh-teacher-addon' ),
			'GI' => esc_html__( 'Gibraltar', 'mkh-teacher-addon' ),
			'GR' => esc_html__( 'Greece', 'mkh-teacher-addon' ),
			'GL' => esc_html__( 'Greenland', 'mkh-teacher-addon' ),
			'GD' => esc_html__( 'Grenada', 'mkh-teacher-addon' ),
			'GP' => esc_html__( 'Guadeloupe', 'mkh-teacher-addon' ),
			'GU' => esc_html__( 'Guam', 'mkh-teacher-addon' ),
			'GT' => esc_html__( 'Guatemala', 'mkh-teacher-addon' ),
			'GN' => esc_html__( 'Guinea', 'mkh-teacher-addon' ),
			'GW' => esc_html__( 'Guinea-Bissau', 'mkh-teacher-addon' ),
			'GY' => esc_html__( 'Guyana', 'mkh-teacher-addon' ),
			'HT' => esc_html__( 'Haiti', 'mkh-teacher-addon' ),
			'HM' => esc_html__( 'Heard Island and Mcdonald Islands', 'mkh-teacher-addon' ),
			'VA' => esc_html__( 'Holy See (Vatican City State)', 'mkh-teacher-addon' ),
			'HN' => esc_html__( 'Honduras', 'mkh-teacher-addon' ),
			'HK' => esc_html__( 'Hong Kong', 'mkh-teacher-addon' ),
			'HU' => esc_html__( 'Hungary', 'mkh-teacher-addon' ),
			'IS' => esc_html__( 'Iceland', 'mkh-teacher-addon' ),
			'IN' => esc_html__( 'India', 'mkh-teacher-addon' ),
			'ID' => esc_html__( 'Indonesia', 'mkh-teacher-addon' ),
			'IR' => esc_html__( 'Iran, Islamic Republic of', 'mkh-teacher-addon' ),
			'IQ' => esc_html__( 'Iraq', 'mkh-teacher-addon' ),
			'IE' => esc_html__( 'Ireland', 'mkh-teacher-addon' ),
			'IL' => esc_html__( 'Israel', 'mkh-teacher-addon' ),
			'IT' => esc_html__( 'Italy', 'mkh-teacher-addon' ),
			'JM' => esc_html__( 'Jamaica', 'mkh-teacher-addon' ),
			'JP' => esc_html__( 'Japan', 'mkh-teacher-addon' ),
			'JO' => esc_html__( 'Jordan', 'mkh-teacher-addon' ),
			'KZ' => esc_html__( 'Kazakhstan', 'mkh-teacher-addon' ),
			'KE' => esc_html__( 'Kenya', 'mkh-teacher-addon' ),
			'KI' => esc_html__( 'Kiribati', 'mkh-teacher-addon' ),
			'KP' => esc_html__( 'Korea, Democratic People\'s Republic of', 'mkh-teacher-addon' ),
			'KR' => esc_html__( 'Korea, Republic of', 'mkh-teacher-addon' ),
			'KW' => esc_html__( 'Kuwait', 'mkh-teacher-addon' ),
			'KG' => esc_html__( 'Kyrgyzstan', 'mkh-teacher-addon' ),
			'LA' => esc_html__( 'Lao People\'s Democratic Republic', 'mkh-teacher-addon' ),
			'LV' => esc_html__( 'Latvia', 'mkh-teacher-addon' ),
			'LB' => esc_html__( 'Lebanon', 'mkh-teacher-addon' ),
			'LS' => esc_html__( 'Lesotho', 'mkh-teacher-addon' ),
			'LR' => esc_html__( 'Liberia', 'mkh-teacher-addon' ),
			'LY' => esc_html__( 'Libyan Arab Jamahiriya', 'mkh-teacher-addon' ),
			'LI' => esc_html__( 'Liechtenstein', 'mkh-teacher-addon' ),
			'LT' => esc_html__( 'Lithuania', 'mkh-teacher-addon' ),
			'LU' => esc_html__( 'Luxembourg', 'mkh-teacher-addon' ),
			'MO' => esc_html__( 'Macao', 'mkh-teacher-addon' ),
			'MK' => esc_html__( 'Macedonia, The Former Yugoslav Republic of', 'mkh-teacher-addon' ),
			'MG' => esc_html__( 'Madagascar', 'mkh-teacher-addon' ),
			'MW' => esc_html__( 'Malawi', 'mkh-teacher-addon' ),
			'MY' => esc_html__( 'Malaysia', 'mkh-teacher-addon' ),
			'MV' => esc_html__( 'Maldives', 'mkh-teacher-addon' ),
			'ML' => esc_html__( 'Mali', 'mkh-teacher-addon' ),
			'MT' => esc_html__( 'Malta', 'mkh-teacher-addon' ),
			'MH' => esc_html__( 'Marshall Islands', 'mkh-teacher-addon' ),
			'MQ' => esc_html__( 'Martinique', 'mkh-teacher-addon' ),
			'MR' => esc_html__( 'Mauritania', 'mkh-teacher-addon' ),
			'MU' => esc_html__( 'Mauritius', 'mkh-teacher-addon' ),
			'YT' => esc_html__( 'Mayotte', 'mkh-teacher-addon' ),
			'MX' => esc_html__( 'Mexico', 'mkh-teacher-addon' ),
			'FM' => esc_html__( 'Micronesia, Federated States of', 'mkh-teacher-addon' ),
			'MD' => esc_html__( 'Moldova, Republic of', 'mkh-teacher-addon' ),
			'MC' => esc_html__( 'Monaco', 'mkh-teacher-addon' ),
			'MN' => esc_html__( 'Mongolia', 'mkh-teacher-addon' ),
			'MS' => esc_html__( 'Montserrat', 'mkh-teacher-addon' ),
			'MA' => esc_html__( 'Morocco', 'mkh-teacher-addon' ),
			'MZ' => esc_html__( 'Mozambique', 'mkh-teacher-addon' ),
			'MM' => esc_html__( 'Myanmar', 'mkh-teacher-addon' ),
			'NA' => esc_html__( 'Namibia', 'mkh-teacher-addon' ),
			'NR' => esc_html__( 'Nauru', 'mkh-teacher-addon' ),
			'NP' => esc_html__( 'Nepal', 'mkh-teacher-addon' ),
			'NL' => esc_html__( 'Netherlands', 'mkh-teacher-addon' ),
			'AN' => esc_html__( 'Netherlands Antilles', 'mkh-teacher-addon' ),
			'NC' => esc_html__( 'New Caledonia', 'mkh-teacher-addon' ),
			'NZ' => esc_html__( 'New Zealand', 'mkh-teacher-addon' ),
			'NI' => esc_html__( 'Nicaragua', 'mkh-teacher-addon' ),
			'NE' => esc_html__( 'Niger', 'mkh-teacher-addon' ),
			'NG' => esc_html__( 'Nigeria', 'mkh-teacher-addon' ),
			'NU' => esc_html__( 'Niue', 'mkh-teacher-addon' ),
			'NF' => esc_html__( 'Norfolk Island', 'mkh-teacher-addon' ),
			'MP' => esc_html__( 'Northern Mariana Islands', 'mkh-teacher-addon' ),
			'NO' => esc_html__( 'Norway', 'mkh-teacher-addon' ),
			'OM' => esc_html__( 'Oman', 'mkh-teacher-addon' ),
			'PK' => esc_html__( 'Pakistan', 'mkh-teacher-addon' ),
			'PW' => esc_html__( 'Palau', 'mkh-teacher-addon' ),
			'PS' => esc_html__( 'Palestinian Territory, Occupied', 'mkh-teacher-addon' ),
			'PA' => esc_html__( 'Panama', 'mkh-teacher-addon' ),
			'PG' => esc_html__( 'Papua New Guinea', 'mkh-teacher-addon' ),
			'PY' => esc_html__( 'Paraguay', 'mkh-teacher-addon' ),
			'PE' => esc_html__( 'Peru', 'mkh-teacher-addon' ),
			'PH' => esc_html__( 'Philippines', 'mkh-teacher-addon' ),
			'PN' => esc_html__( 'Pitcairn', 'mkh-teacher-addon' ),
			'PL' => esc_html__( 'Poland', 'mkh-teacher-addon' ),
			'PT' => esc_html__( 'Portugal', 'mkh-teacher-addon' ),
			'PR' => esc_html__( 'Puerto Rico', 'mkh-teacher-addon' ),
			'QA' => esc_html__( 'Qatar', 'mkh-teacher-addon' ),
			'RE' => esc_html__( 'Reunion', 'mkh-teacher-addon' ),
			'RO' => esc_html__( 'Romania', 'mkh-teacher-addon' ),
			'RU' => esc_html__( 'Russian Federation', 'mkh-teacher-addon' ),
			'RW' => esc_html__( 'Rwanda', 'mkh-teacher-addon' ),
			'KN' => esc_html__( 'Saint Kitts and Nevis', 'mkh-teacher-addon' ),
			'LC' => esc_html__( 'Saint Lucia', 'mkh-teacher-addon' ),
			'VC' => esc_html__( 'Saint Vincent and the Grenadines', 'mkh-teacher-addon' ),
			'WS' => esc_html__( 'Samoa', 'mkh-teacher-addon' ),
			'SM' => esc_html__( 'San Marino', 'mkh-teacher-addon' ),
			'ST' => esc_html__( 'Sao Tome and Principe', 'mkh-teacher-addon' ),
			'SA' => esc_html__( 'Saudi Arabia', 'mkh-teacher-addon' ),
			'SN' => esc_html__( 'Senegal', 'mkh-teacher-addon' ),
			'SC' => esc_html__( 'Seychelles', 'mkh-teacher-addon' ),
			'SL' => esc_html__( 'Sierra Leone', 'mkh-teacher-addon' ),
			'SG' => esc_html__( 'Singapore', 'mkh-teacher-addon' ),
			'SK' => esc_html__( 'Slovakia', 'mkh-teacher-addon' ),
			'SI' => esc_html__( 'Slovenia', 'mkh-teacher-addon' ),
			'SB' => esc_html__( 'Solomon Islands', 'mkh-teacher-addon' ),
			'SO' => esc_html__( 'Somalia', 'mkh-teacher-addon' ),
			'ZA' => esc_html__( 'South Africa', 'mkh-teacher-addon' ),
			'GS' => esc_html__( 'South Georgia and the South Sandwich Islands', 'mkh-teacher-addon' ),
			'ES' => esc_html__( 'Spain', 'mkh-teacher-addon' ),
			'LK' => esc_html__( 'Sri Lanka', 'mkh-teacher-addon' ),
			'SH' => esc_html__( 'St. Helena', 'mkh-teacher-addon' ),
			'SD' => esc_html__( 'Sudan', 'mkh-teacher-addon' ),
			'SR' => esc_html__( 'Suriname', 'mkh-teacher-addon' ),
			'SJ' => esc_html__( 'Svalbard and Jan Mayen', 'mkh-teacher-addon' ),
			'SZ' => esc_html__( 'Swaziland', 'mkh-teacher-addon' ),
			'SE' => esc_html__( 'Sweden', 'mkh-teacher-addon' ),
			'CH' => esc_html__( 'Switzerland', 'mkh-teacher-addon' ),
			'SY' => esc_html__( 'Syrian Arab Republic', 'mkh-teacher-addon' ),
			'TW' => esc_html__( 'Taiwan, Province of China', 'mkh-teacher-addon' ),
			'TJ' => esc_html__( 'Tajikistan', 'mkh-teacher-addon' ),
			'TZ' => esc_html__( 'Tanzania, United Republic of', 'mkh-teacher-addon' ),
			'TH' => esc_html__( 'Thailand', 'mkh-teacher-addon' ),
			'TG' => esc_html__( 'Togo', 'mkh-teacher-addon' ),
			'TK' => esc_html__( 'Tokelau', 'mkh-teacher-addon' ),
			'TO' => esc_html__( 'Tonga', 'mkh-teacher-addon' ),
			'TT' => esc_html__( 'Trinidad and Tobago', 'mkh-teacher-addon' ),
			'TN' => esc_html__( 'Tunisia', 'mkh-teacher-addon' ),
			'TR' => esc_html__( 'Turkey', 'mkh-teacher-addon' ),
			'TM' => esc_html__( 'Turkmenistan', 'mkh-teacher-addon' ),
			'TC' => esc_html__( 'Turks and Caicos Islands', 'mkh-teacher-addon' ),
			'TV' => esc_html__( 'Tuvalu', 'mkh-teacher-addon' ),
			'UG' => esc_html__( 'Uganda', 'mkh-teacher-addon' ),
			'UA' => esc_html__( 'Ukraine', 'mkh-teacher-addon' ),
			'AE' => esc_html__( 'United Arab Emirates', 'mkh-teacher-addon' ),
			'GB' => esc_html__( 'United Kingdom', 'mkh-teacher-addon' ),
			'US' => esc_html__( 'United States', 'mkh-teacher-addon' ),
			'UM' => esc_html__( 'United States Minor Outlying Islands', 'mkh-teacher-addon' ),
			'UY' => esc_html__( 'Uruguay', 'mkh-teacher-addon' ),
			'UZ' => esc_html__( 'Uzbekistan', 'mkh-teacher-addon' ),
			'VU' => esc_html__( 'Vanuatu', 'mkh-teacher-addon' ),
			'VE' => esc_html__( 'Venezuela', 'mkh-teacher-addon' ),
			'VN' => esc_html__( 'Viet Nam', 'mkh-teacher-addon' ),
			'VG' => esc_html__( 'Virgin Islands, British', 'mkh-teacher-addon' ),
			'VI' => esc_html__( 'Virgin Islands, U.S.', 'mkh-teacher-addon' ),
			'WF' => esc_html__( 'Wallis and Futuna', 'mkh-teacher-addon' ),
			'EH' => esc_html__( 'Western Sahara', 'mkh-teacher-addon' ),
			'YE' => esc_html__( 'Yemen', 'mkh-teacher-addon' ),
			'ZM' => esc_html__( 'Zambia', 'mkh-teacher-addon' ),
			'ZW' => esc_html__( 'Zimbabwe', 'mkh-teacher-addon' ),
		);

		// Sort countries alphabetically by name
		asort( $countries );

		return $countries;
	}

	/**
	 * Get timezone choices for select field.
	 *
	 * @return array<string, string> Timezone choices.
	 */
	private function get_timezone_choices() {
		$timezones = array(
			'UTC' => 'UTC',
			'Africa/Abidjan' => 'Africa/Abidjan',
			'Africa/Accra' => 'Africa/Accra',
			'Africa/Addis_Ababa' => 'Africa/Addis_Ababa',
			'Africa/Algiers' => 'Africa/Algiers',
			'Africa/Asmara' => 'Africa/Asmara',
			'Africa/Bamako' => 'Africa/Bamako',
			'Africa/Bangui' => 'Africa/Bangui',
			'Africa/Banjul' => 'Africa/Banjul',
			'Africa/Bissau' => 'Africa/Bissau',
			'Africa/Blantyre' => 'Africa/Blantyre',
			'Africa/Brazzaville' => 'Africa/Brazzaville',
			'Africa/Bujumbura' => 'Africa/Bujumbura',
			'Africa/Cairo' => 'Africa/Cairo',
			'Africa/Casablanca' => 'Africa/Casablanca',
			'Africa/Ceuta' => 'Africa/Ceuta',
			'Africa/Conakry' => 'Africa/Conakry',
			'Africa/Dakar' => 'Africa/Dakar',
			'Africa/Dar_es_Salaam' => 'Africa/Dar_es_Salaam',
			'Africa/Djibouti' => 'Africa/Djibouti',
			'Africa/Douala' => 'Africa/Douala',
			'Africa/El_Aaiun' => 'Africa/El_Aaiun',
			'Africa/Freetown' => 'Africa/Freetown',
			'Africa/Gaborone' => 'Africa/Gaborone',
			'Africa/Harare' => 'Africa/Harare',
			'Africa/Johannesburg' => 'Africa/Johannesburg',
			'Africa/Juba' => 'Africa/Juba',
			'Africa/Kampala' => 'Africa/Kampala',
			'Africa/Khartoum' => 'Africa/Khartoum',
			'Africa/Kigali' => 'Africa/Kigali',
			'Africa/Kinshasa' => 'Africa/Kinshasa',
			'Africa/Lagos' => 'Africa/Lagos',
			'Africa/Libreville' => 'Africa/Libreville',
			'Africa/Lome' => 'Africa/Lome',
			'Africa/Luanda' => 'Africa/Luanda',
			'Africa/Lubumbashi' => 'Africa/Lubumbashi',
			'Africa/Lusaka' => 'Africa/Lusaka',
			'Africa/Malabo' => 'Africa/Malabo',
			'Africa/Maputo' => 'Africa/Maputo',
			'Africa/Maseru' => 'Africa/Maseru',
			'Africa/Mbabane' => 'Africa/Mbabane',
			'Africa/Mogadishu' => 'Africa/Mogadishu',
			'Africa/Monrovia' => 'Africa/Monrovia',
			'Africa/Nairobi' => 'Africa/Nairobi',
			'Africa/Ndjamena' => 'Africa/Ndjamena',
			'Africa/Niamey' => 'Africa/Niamey',
			'Africa/Nouakchott' => 'Africa/Nouakchott',
			'Africa/Ouagadougou' => 'Africa/Ouagadougou',
			'Africa/Porto-Novo' => 'Africa/Porto-Novo',
			'Africa/Sao_Tome' => 'Africa/Sao_Tome',
			'Africa/Tripoli' => 'Africa/Tripoli',
			'Africa/Tunis' => 'Africa/Tunis',
			'Africa/Windhoek' => 'Africa/Windhoek',
			'America/Adak' => 'America/Adak',
			'America/Anchorage' => 'America/Anchorage',
			'America/Anguilla' => 'America/Anguilla',
			'America/Antigua' => 'America/Antigua',
			'America/Araguaina' => 'America/Araguaina',
			'America/Argentina/Buenos_Aires' => 'America/Argentina/Buenos_Aires',
			'America/Argentina/Catamarca' => 'America/Argentina/Catamarca',
			'America/Argentina/Cordoba' => 'America/Argentina/Cordoba',
			'America/Argentina/Jujuy' => 'America/Argentina/Jujuy',
			'America/Argentina/La_Rioja' => 'America/Argentina/La_Rioja',
			'America/Argentina/Mendoza' => 'America/Argentina/Mendoza',
			'America/Argentina/Rio_Gallegos' => 'America/Argentina/Rio_Gallegos',
			'America/Argentina/Salta' => 'America/Argentina/Salta',
			'America/Argentina/San_Juan' => 'America/Argentina/San_Juan',
			'America/Argentina/San_Luis' => 'America/Argentina/San_Luis',
			'America/Argentina/Tucuman' => 'America/Argentina/Tucuman',
			'America/Argentina/Ushuaia' => 'America/Argentina/Ushuaia',
			'America/Aruba' => 'America/Aruba',
			'America/Asuncion' => 'America/Asuncion',
			'America/Atikokan' => 'America/Atikokan',
			'America/Bahia' => 'America/Bahia',
			'America/Bahia_Banderas' => 'America/Bahia_Banderas',
			'America/Barbados' => 'America/Barbados',
			'America/Belem' => 'America/Belem',
			'America/Belize' => 'America/Belize',
			'America/Blanc-Sablon' => 'America/Blanc-Sablon',
			'America/Boa_Vista' => 'America/Boa_Vista',
			'America/Bogota' => 'America/Bogota',
			'America/Boise' => 'America/Boise',
			'America/Cambridge_Bay' => 'America/Cambridge_Bay',
			'America/Campo_Grande' => 'America/Campo_Grande',
			'America/Cancun' => 'America/Cancun',
			'America/Caracas' => 'America/Caracas',
			'America/Cayenne' => 'America/Cayenne',
			'America/Cayman' => 'America/Cayman',
			'America/Chicago' => 'America/Chicago',
			'America/Chihuahua' => 'America/Chihuahua',
			'America/Costa_Rica' => 'America/Costa_Rica',
			'America/Creston' => 'America/Creston',
			'America/Cuiaba' => 'America/Cuiaba',
			'America/Curacao' => 'America/Curacao',
			'America/Danmarkshavn' => 'America/Danmarkshavn',
			'America/Dawson' => 'America/Dawson',
			'America/Dawson_Creek' => 'America/Dawson_Creek',
			'America/Denver' => 'America/Denver',
			'America/Detroit' => 'America/Detroit',
			'America/Dominica' => 'America/Dominica',
			'America/Edmonton' => 'America/Edmonton',
			'America/Eirunepe' => 'America/Eirunepe',
			'America/El_Salvador' => 'America/El_Salvador',
			'America/Fort_Nelson' => 'America/Fort_Nelson',
			'America/Fortaleza' => 'America/Fortaleza',
			'America/Glace_Bay' => 'America/Glace_Bay',
			'America/Godthab' => 'America/Godthab',
			'America/Goose_Bay' => 'America/Goose_Bay',
			'America/Grand_Turk' => 'America/Grand_Turk',
			'America/Grenada' => 'America/Grenada',
			'America/Guadeloupe' => 'America/Guadeloupe',
			'America/Guatemala' => 'America/Guatemala',
			'America/Guayaquil' => 'America/Guayaquil',
			'America/Guyana' => 'America/Guyana',
			'America/Halifax' => 'America/Halifax',
			'America/Havana' => 'America/Havana',
			'America/Hermosillo' => 'America/Hermosillo',
			'America/Indiana/Indianapolis' => 'America/Indiana/Indianapolis',
			'America/Indiana/Knox' => 'America/Indiana/Knox',
			'America/Indiana/Marengo' => 'America/Indiana/Marengo',
			'America/Indiana/Petersburg' => 'America/Indiana/Petersburg',
			'America/Indiana/Tell_City' => 'America/Indiana/Tell_City',
			'America/Indiana/Vevay' => 'America/Indiana/Vevay',
			'America/Indiana/Vincennes' => 'America/Indiana/Vincennes',
			'America/Indiana/Winamac' => 'America/Indiana/Winamac',
			'America/Inuvik' => 'America/Inuvik',
			'America/Iqaluit' => 'America/Iqaluit',
			'America/Jamaica' => 'America/Jamaica',
			'America/Juneau' => 'America/Juneau',
			'America/Kentucky/Louisville' => 'America/Kentucky/Louisville',
			'America/Kentucky/Monticello' => 'America/Kentucky/Monticello',
			'America/Kralendijk' => 'America/Kralendijk',
			'America/La_Paz' => 'America/La_Paz',
			'America/Lima' => 'America/Lima',
			'America/Los_Angeles' => 'America/Los_Angeles',
			'America/Lower_Princes' => 'America/Lower_Princes',
			'America/Maceio' => 'America/Maceio',
			'America/Managua' => 'America/Managua',
			'America/Manaus' => 'America/Manaus',
			'America/Marigot' => 'America/Marigot',
			'America/Martinique' => 'America/Martinique',
			'America/Matamoros' => 'America/Matamoros',
			'America/Mazatlan' => 'America/Mazatlan',
			'America/Menominee' => 'America/Menominee',
			'America/Merida' => 'America/Merida',
			'America/Metlakatla' => 'America/Metlakatla',
			'America/Mexico_City' => 'America/Mexico_City',
			'America/Miquelon' => 'America/Miquelon',
			'America/Moncton' => 'America/Moncton',
			'America/Monterrey' => 'America/Monterrey',
			'America/Montevideo' => 'America/Montevideo',
			'America/Montreal' => 'America/Montreal',
			'America/Montserrat' => 'America/Montserrat',
			'America/Nassau' => 'America/Nassau',
			'America/New_York' => 'America/New_York',
			'America/Nipigon' => 'America/Nipigon',
			'America/Nome' => 'America/Nome',
			'America/Noronha' => 'America/Noronha',
			'America/North_Dakota/Beulah' => 'America/North_Dakota/Beulah',
			'America/North_Dakota/Center' => 'America/North_Dakota/Center',
			'America/North_Dakota/New_Salem' => 'America/North_Dakota/New_Salem',
			'America/Ojinaga' => 'America/Ojinaga',
			'America/Panama' => 'America/Panama',
			'America/Pangnirtung' => 'America/Pangnirtung',
			'America/Paramaribo' => 'America/Paramaribo',
			'America/Phoenix' => 'America/Phoenix',
			'America/Port-au-Prince' => 'America/Port-au-Prince',
			'America/Port_of_Spain' => 'America/Port_of_Spain',
			'America/Porto_Velho' => 'America/Porto_Velho',
			'America/Puerto_Rico' => 'America/Puerto_Rico',
			'America/Punta_Arenas' => 'America/Punta_Arenas',
			'America/Rankin_Inlet' => 'America/Rankin_Inlet',
			'America/Recife' => 'America/Recife',
			'America/Regina' => 'America/Regina',
			'America/Resolute' => 'America/Resolute',
			'America/Rio_Branco' => 'America/Rio_Branco',
			'America/Santarem' => 'America/Santarem',
			'America/Santiago' => 'America/Santiago',
			'America/Santo_Domingo' => 'America/Santo_Domingo',
			'America/Sao_Paulo' => 'America/Sao_Paulo',
			'America/Scoresbysund' => 'America/Scoresbysund',
			'America/Sitka' => 'America/Sitka',
			'America/St_Barthelemy' => 'America/St_Barthelemy',
			'America/St_Johns' => 'America/St_Johns',
			'America/St_Kitts' => 'America/St_Kitts',
			'America/St_Lucia' => 'America/St_Lucia',
			'America/St_Thomas' => 'America/St_Thomas',
			'America/St_Vincent' => 'America/St_Vincent',
			'America/Swift_Current' => 'America/Swift_Current',
			'America/Tegucigalpa' => 'America/Tegucigalpa',
			'America/Thule' => 'America/Thule',
			'America/Thunder_Bay' => 'America/Thunder_Bay',
			'America/Tijuana' => 'America/Tijuana',
			'America/Toronto' => 'America/Toronto',
			'America/Tortola' => 'America/Tortola',
			'America/Vancouver' => 'America/Vancouver',
			'America/Whitehorse' => 'America/Whitehorse',
			'America/Winnipeg' => 'America/Winnipeg',
			'America/Yakutat' => 'America/Yakutat',
			'America/Yellowknife' => 'America/Yellowknife',
			'Antarctica/Casey' => 'Antarctica/Casey',
			'Antarctica/Davis' => 'Antarctica/Davis',
			'Antarctica/DumontDUrville' => 'Antarctica/DumontDUrville',
			'Antarctica/Macquarie' => 'Antarctica/Macquarie',
			'Antarctica/Mawson' => 'Antarctica/Mawson',
			'Antarctica/McMurdo' => 'Antarctica/McMurdo',
			'Antarctica/Palmer' => 'Antarctica/Palmer',
			'Antarctica/Rothera' => 'Antarctica/Rothera',
			'Antarctica/Syowa' => 'Antarctica/Syowa',
			'Antarctica/Troll' => 'Antarctica/Troll',
			'Antarctica/Vostok' => 'Antarctica/Vostok',
			'Arctic/Longyearbyen' => 'Arctic/Longyearbyen',
			'Asia/Aden' => 'Asia/Aden',
			'Asia/Almaty' => 'Asia/Almaty',
			'Asia/Amman' => 'Asia/Amman',
			'Asia/Anadyr' => 'Asia/Anadyr',
			'Asia/Aqtau' => 'Asia/Aqtau',
			'Asia/Aqtobe' => 'Asia/Aqtobe',
			'Asia/Ashgabat' => 'Asia/Ashgabat',
			'Asia/Atyrau' => 'Asia/Atyrau',
			'Asia/Baghdad' => 'Asia/Baghdad',
			'Asia/Bahrain' => 'Asia/Bahrain',
			'Asia/Baku' => 'Asia/Baku',
			'Asia/Bangkok' => 'Asia/Bangkok',
			'Asia/Barnaul' => 'Asia/Barnaul',
			'Asia/Beirut' => 'Asia/Beirut',
			'Asia/Bishkek' => 'Asia/Bishkek',
			'Asia/Brunei' => 'Asia/Brunei',
			'Asia/Chita' => 'Asia/Chita',
			'Asia/Choibalsan' => 'Asia/Choibalsan',
			'Asia/Colombo' => 'Asia/Colombo',
			'Asia/Damascus' => 'Asia/Damascus',
			'Asia/Dhaka' => 'Asia/Dhaka',
			'Asia/Dili' => 'Asia/Dili',
			'Asia/Dubai' => 'Asia/Dubai',
			'Asia/Dushanbe' => 'Asia/Dushanbe',
			'Asia/Famagusta' => 'Asia/Famagusta',
			'Asia/Gaza' => 'Asia/Gaza',
			'Asia/Hebron' => 'Asia/Hebron',
			'Asia/Ho_Chi_Minh' => 'Asia/Ho_Chi_Minh',
			'Asia/Hong_Kong' => 'Asia/Hong_Kong',
			'Asia/Hovd' => 'Asia/Hovd',
			'Asia/Irkutsk' => 'Asia/Irkutsk',
			'Asia/Jakarta' => 'Asia/Jakarta',
			'Asia/Jayapura' => 'Asia/Jayapura',
			'Asia/Jerusalem' => 'Asia/Jerusalem',
			'Asia/Kabul' => 'Asia/Kabul',
			'Asia/Kamchatka' => 'Asia/Kamchatka',
			'Asia/Karachi' => 'Asia/Karachi',
			'Asia/Kathmandu' => 'Asia/Kathmandu',
			'Asia/Khandyga' => 'Asia/Khandyga',
			'Asia/Kolkata' => 'Asia/Kolkata',
			'Asia/Krasnoyarsk' => 'Asia/Krasnoyarsk',
			'Asia/Kuala_Lumpur' => 'Asia/Kuala_Lumpur',
			'Asia/Kuching' => 'Asia/Kuching',
			'Asia/Kuwait' => 'Asia/Kuwait',
			'Asia/Macau' => 'Asia/Macau',
			'Asia/Magadan' => 'Asia/Magadan',
			'Asia/Makassar' => 'Asia/Makassar',
			'Asia/Manila' => 'Asia/Manila',
			'Asia/Muscat' => 'Asia/Muscat',
			'Asia/Nicosia' => 'Asia/Nicosia',
			'Asia/Novokuznetsk' => 'Asia/Novokuznetsk',
			'Asia/Novosibirsk' => 'Asia/Novosibirsk',
			'Asia/Omsk' => 'Asia/Omsk',
			'Asia/Oral' => 'Asia/Oral',
			'Asia/Phnom_Penh' => 'Asia/Phnom_Penh',
			'Asia/Pontianak' => 'Asia/Pontianak',
			'Asia/Pyongyang' => 'Asia/Pyongyang',
			'Asia/Qatar' => 'Asia/Qatar',
			'Asia/Qostanay' => 'Asia/Qostanay',
			'Asia/Qyzylorda' => 'Asia/Qyzylorda',
			'Asia/Riyadh' => 'Asia/Riyadh',
			'Asia/Sakhalin' => 'Asia/Sakhalin',
			'Asia/Samarkand' => 'Asia/Samarkand',
			'Asia/Seoul' => 'Asia/Seoul',
			'Asia/Shanghai' => 'Asia/Shanghai',
			'Asia/Singapore' => 'Asia/Singapore',
			'Asia/Srednekolymsk' => 'Asia/Srednekolymsk',
			'Asia/Taipei' => 'Asia/Taipei',
			'Asia/Tashkent' => 'Asia/Tashkent',
			'Asia/Tbilisi' => 'Asia/Tbilisi',
			'Asia/Tehran' => 'Asia/Tehran',
			'Asia/Thimphu' => 'Asia/Thimphu',
			'Asia/Tokyo' => 'Asia/Tokyo',
			'Asia/Tomsk' => 'Asia/Tomsk',
			'Asia/Ulaanbaatar' => 'Asia/Ulaanbaatar',
			'Asia/Urumqi' => 'Asia/Urumqi',
			'Asia/Ust-Nera' => 'Asia/Ust-Nera',
			'Asia/Vientiane' => 'Asia/Vientiane',
			'Asia/Vladivostok' => 'Asia/Vladivostok',
			'Asia/Yakutsk' => 'Asia/Yakutsk',
			'Asia/Yangon' => 'Asia/Yangon',
			'Asia/Yekaterinburg' => 'Asia/Yekaterinburg',
			'Asia/Yerevan' => 'Asia/Yerevan',
			'Atlantic/Azores' => 'Atlantic/Azores',
			'Atlantic/Bermuda' => 'Atlantic/Bermuda',
			'Atlantic/Canary' => 'Atlantic/Canary',
			'Atlantic/Cape_Verde' => 'Atlantic/Cape_Verde',
			'Atlantic/Faroe' => 'Atlantic/Faroe',
			'Atlantic/Madeira' => 'Atlantic/Madeira',
			'Atlantic/Reykjavik' => 'Atlantic/Reykjavik',
			'Atlantic/South_Georgia' => 'Atlantic/South_Georgia',
			'Atlantic/St_Helena' => 'Atlantic/St_Helena',
			'Atlantic/Stanley' => 'Atlantic/Stanley',
			'Australia/Adelaide' => 'Australia/Adelaide',
			'Australia/Brisbane' => 'Australia/Brisbane',
			'Australia/Broken_Hill' => 'Australia/Broken_Hill',
			'Australia/Currie' => 'Australia/Currie',
			'Australia/Darwin' => 'Australia/Darwin',
			'Australia/Eucla' => 'Australia/Eucla',
			'Australia/Hobart' => 'Australia/Hobart',
			'Australia/Lindeman' => 'Australia/Lindeman',
			'Australia/Lord_Howe' => 'Australia/Lord_Howe',
			'Australia/Melbourne' => 'Australia/Melbourne',
			'Australia/Perth' => 'Australia/Perth',
			'Australia/Sydney' => 'Australia/Sydney',
			'Europe/Amsterdam' => 'Europe/Amsterdam',
			'Europe/Andorra' => 'Europe/Andorra',
			'Europe/Astrakhan' => 'Europe/Astrakhan',
			'Europe/Athens' => 'Europe/Athens',
			'Europe/Belgrade' => 'Europe/Belgrade',
			'Europe/Berlin' => 'Europe/Berlin',
			'Europe/Bratislava' => 'Europe/Bratislava',
			'Europe/Brussels' => 'Europe/Brussels',
			'Europe/Bucharest' => 'Europe/Bucharest',
			'Europe/Budapest' => 'Europe/Budapest',
			'Europe/Busingen' => 'Europe/Busingen',
			'Europe/Chisinau' => 'Europe/Chisinau',
			'Europe/Copenhagen' => 'Europe/Copenhagen',
			'Europe/Dublin' => 'Europe/Dublin',
			'Europe/Gibraltar' => 'Europe/Gibraltar',
			'Europe/Guernsey' => 'Europe/Guernsey',
			'Europe/Helsinki' => 'Europe/Helsinki',
			'Europe/Isle_of_Man' => 'Europe/Isle_of_Man',
			'Europe/Istanbul' => 'Europe/Istanbul',
			'Europe/Jersey' => 'Europe/Jersey',
			'Europe/Kaliningrad' => 'Europe/Kaliningrad',
			'Europe/Kiev' => 'Europe/Kiev',
			'Europe/Kirov' => 'Europe/Kirov',
			'Europe/Lisbon' => 'Europe/Lisbon',
			'Europe/Ljubljana' => 'Europe/Ljubljana',
			'Europe/London' => 'Europe/London',
			'Europe/Luxembourg' => 'Europe/Luxembourg',
			'Europe/Madrid' => 'Europe/Madrid',
			'Europe/Malta' => 'Europe/Malta',
			'Europe/Mariehamn' => 'Europe/Mariehamn',
			'Europe/Minsk' => 'Europe/Minsk',
			'Europe/Monaco' => 'Europe/Monaco',
			'Europe/Moscow' => 'Europe/Moscow',
			'Europe/Oslo' => 'Europe/Oslo',
			'Europe/Paris' => 'Europe/Paris',
			'Europe/Podgorica' => 'Europe/Podgorica',
			'Europe/Prague' => 'Europe/Prague',
			'Europe/Riga' => 'Europe/Riga',
			'Europe/Rome' => 'Europe/Rome',
			'Europe/Samara' => 'Europe/Samara',
			'Europe/San_Marino' => 'Europe/San_Marino',
			'Europe/Sarajevo' => 'Europe/Sarajevo',
			'Europe/Saratov' => 'Europe/Saratov',
			'Europe/Simferopol' => 'Europe/Simferopol',
			'Europe/Skopje' => 'Europe/Skopje',
			'Europe/Sofia' => 'Europe/Sofia',
			'Europe/Stockholm' => 'Europe/Stockholm',
			'Europe/Tallinn' => 'Europe/Tallinn',
			'Europe/Tirane' => 'Europe/Tirane',
			'Europe/Ulyanovsk' => 'Europe/Ulyanovsk',
			'Europe/Uzhgorod' => 'Europe/Uzhgorod',
			'Europe/Vaduz' => 'Europe/Vaduz',
			'Europe/Vatican' => 'Europe/Vatican',
			'Europe/Vienna' => 'Europe/Vienna',
			'Europe/Vilnius' => 'Europe/Vilnius',
			'Europe/Volgograd' => 'Europe/Volgograd',
			'Europe/Warsaw' => 'Europe/Warsaw',
			'Europe/Zagreb' => 'Europe/Zagreb',
			'Europe/Zaporozhye' => 'Europe/Zaporozhye',
			'Europe/Zurich' => 'Europe/Zurich',
			'Indian/Antananarivo' => 'Indian/Antananarivo',
			'Indian/Chagos' => 'Indian/Chagos',
			'Indian/Christmas' => 'Indian/Christmas',
			'Indian/Cocos' => 'Indian/Cocos',
			'Indian/Comoro' => 'Indian/Comoro',
			'Indian/Kerguelen' => 'Indian/Kerguelen',
			'Indian/Mahe' => 'Indian/Mahe',
			'Indian/Maldives' => 'Indian/Maldives',
			'Indian/Mauritius' => 'Indian/Mauritius',
			'Indian/Mayotte' => 'Indian/Mayotte',
			'Indian/Reunion' => 'Indian/Reunion',
			'Pacific/Apia' => 'Pacific/Apia',
			'Pacific/Auckland' => 'Pacific/Auckland',
			'Pacific/Bougainville' => 'Pacific/Bougainville',
			'Pacific/Chatham' => 'Pacific/Chatham',
			'Pacific/Chuuk' => 'Pacific/Chuuk',
			'Pacific/Easter' => 'Pacific/Easter',
			'Pacific/Efate' => 'Pacific/Efate',
			'Pacific/Fakaofo' => 'Pacific/Fakaofo',
			'Pacific/Fiji' => 'Pacific/Fiji',
			'Pacific/Funafuti' => 'Pacific/Funafuti',
			'Pacific/Galapagos' => 'Pacific/Galapagos',
			'Pacific/Gambier' => 'Pacific/Gambier',
			'Pacific/Guadalcanal' => 'Pacific/Guadalcanal',
			'Pacific/Guam' => 'Pacific/Guam',
			'Pacific/Honolulu' => 'Pacific/Honolulu',
			'Pacific/Kiritimati' => 'Pacific/Kiritimati',
			'Pacific/Kosrae' => 'Pacific/Kosrae',
			'Pacific/Kwajalein' => 'Pacific/Kwajalein',
			'Pacific/Majuro' => 'Pacific/Majuro',
			'Pacific/Marquesas' => 'Pacific/Marquesas',
			'Pacific/Midway' => 'Pacific/Midway',
			'Pacific/Nauru' => 'Pacific/Nauru',
			'Pacific/Niue' => 'Pacific/Niue',
			'Pacific/Norfolk' => 'Pacific/Norfolk',
			'Pacific/Noumea' => 'Pacific/Noumea',
			'Pacific/Pago_Pago' => 'Pacific/Pago_Pago',
			'Pacific/Palau' => 'Pacific/Palau',
			'Pacific/Pitcairn' => 'Pacific/Pitcairn',
			'Pacific/Pohnpei' => 'Pacific/Pohnpei',
			'Pacific/Port_Moresby' => 'Pacific/Port_Moresby',
			'Pacific/Rarotonga' => 'Pacific/Rarotonga',
			'Pacific/Saipan' => 'Pacific/Saipan',
			'Pacific/Tahiti' => 'Pacific/Tahiti',
			'Pacific/Tarawa' => 'Pacific/Tarawa',
			'Pacific/Tongatapu' => 'Pacific/Tongatapu',
			'Pacific/Wake' => 'Pacific/Wake',
			'Pacific/Wallis' => 'Pacific/Wallis',
		);

		// Sort timezones alphabetically
		asort( $timezones );

		return $timezones;
	}
}

// Initialize the class
new MKH_Teacher_Profile_ACF();
